### PR TITLE
document model coverage report

### PR DESCRIPTION
**Pull request by mw-hrastega**
Summary of changes:
- Add text and update screenshots
- Incorporate editorial feedback

### CODE REVIEW

**Comment by mcafaro** [comment]
The doc changes look good to me. Why is our CI job failing though?

**Comment by ppandian28** [comment]
> The doc changes look good to me. Why is our CI job failing though?

> Doc looks good Houman. At this point, I think it's a time-out error from waiting on a couple of dependencies, trying to resolve it for now.

**Comment by mw-hrastega** [comment]
> > The doc changes look good to me. Why is our CI job failing though?
> 
> > Doc looks good Houman. At this point, I think it's a time-out error from waiting on a couple of dependencies, trying to resolve it for now.

Thanks Preethi and Mark for your reviews :)

**Comment by ppandian28** [comment]
Job is passing for now. Need to further look into dependencies.

**Pull request merged**
